# This is a basic workflow to help you get started with Actions

name: NodeJS Scan

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: nodejsscan
      id: nodejsscan
      uses: ajinabraham/njsscan-action@v5
      with:
        args: '.'
